POST http://localhost:8080/url
Content-Type: application/json

{
  "TargetUrl": "https://google.com",
  "Token": "0eb34fad-ea88-4840-a084-f2d210400527"
}

###
DELETE http://localhost:8080/url/cv6VxVduxjTiFIFKMqt4VWjtp2o=/0eb34fad-ea88-4840-a084-f2d210400527

###
GET http://localhost:8080/url/0eb34fad-ea88-4840-a084-f2d210400527